version: '3.8'

x-airflow-common:
  &airflow-common
  image: airflow:project-be-analytic-ida-datamart
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./sql:/opt/airflow/sql
    - ./data:/opt/airflow/data
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:17.5-bookworm
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init_datamart.sql:/docker-entrypoint-initdb.d/init_datamart.sql  # <- adiciona aqui

  airflow-webserver:
    <<: *airflow-common
    command: airflow webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    command: airflow scheduler

  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"

  airflow-debug:
    <<: *airflow-common
    command: bash
    stdin_open: true
    tty: true

volumes:
  pgdata:
